version: '3.1'

services:
  test:
    image: docker.io/library/mariadb:latest
    container_name: test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 53306:3306
    volumes:
      - /var/lib/mysql

